apiVersion: v1
kind: Namespace
metadata:
  name: temp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"


---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  namespace: temp
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
