apiVersion: v1
kind: Service
metadata:
  name: prometheus-proxy
  namespace: default
spec:
  type: ExternalName
  externalName: prometheus.monitoring.svc.cluster.local
  ports:
    - port: 9090
      targetPort: 9090




